// <auto-generated>
//     Generated from Sources/MacOnScreenChat/DatingHeat.swift by windows/tools/sync-prompts.py.
//     DO NOT EDIT BY HAND — edit the Swift source and re-run the generator,
//     so the macOS and Windows apps cannot drift apart.
// </auto-generated>

namespace OnScreenChat.Core.Prompts;

/// <summary>Calibration text appended to the dating skill's prompt.</summary>
internal static class DatingHeatText
{
    public const string Cool =
        """


        CALIBRATION: Read her as low interest / cooling off, whatever the thread suggests. Keep all three options light and low-pressure; make the Spicy slot a genuine re-engagement or pattern-break, never a bold move.
        """;

    public const string Warm =
        """


        CALIBRATION: Read her as warm but not fully committed. Moderate escalation — Flirty is fine; keep Spicy suggestive but restrained.
        """;

    public const string Spicy =
        """


        CALIBRATION: She's clearly into it. Escalate confidently — the Spicy option can be genuinely bold and suggestive (still innuendo, never crude or explicit).
        """;

}
