// <auto-generated>
//     Generated from Sources/MacOnScreenChat/{RuleStore,ChatViewModel}.swift by windows/tools/sync-prompts.py.
//     DO NOT EDIT BY HAND — edit the Swift source and re-run the generator,
//     so the macOS and Windows apps cannot drift apart.
// </auto-generated>

namespace OnScreenChat.Core.Prompts;

/// <summary>Prompt blocks that wrap a runtime value; use with string.Format.</summary>
public static class PromptTemplates
{
    /// <summary>{0} is the numbered list of standing rules.</summary>
    public const string StandingRules =
        """


        MY STANDING RULES — I set these myself and they apply to EVERY reply. They outrank the formatting and style guidance above wherever they conflict; only follow-up instructions I give in this message rank higher:
        {0}
        """;

    /// <summary>{0} is the one-shot directive text.</summary>
    public const string Directive =
        """


        HIGHEST-PRIORITY INSTRUCTION FROM ME for this reply — apply it and let it override any conflicting formatting or style rules above:
        {0}
        """;
}
