// <auto-generated>
//     Generated from Sources/MacOnScreenChat/ResponseStyle.swift by windows/tools/sync-prompts.py.
//     DO NOT EDIT BY HAND — edit the Swift source and re-run the generator,
//     so the macOS and Windows apps cannot drift apart.
// </auto-generated>

namespace OnScreenChat.Core.Text;

public static partial class ResponseStyle
{
    /// <summary>Prepended to every system prompt, whatever the skill.</summary>
    public const string Contract = """
        RESPONSE FORMAT — this governs every reply you write:
        - Plain text only. Never write two asterisks anywhere in a reply: no **bold**, no *emphasis*, no _underscores_, no # headings, no backticks and no code fences. Emphasis is carried by word choice, not by symbols.
        - Break the reply into short paragraphs of at most two or three sentences, with exactly ONE blank line between paragraphs. Never return a wall of text.
        - When you list things, put each item on its own line starting with "- " (hyphen, space), and keep one blank line between the list and the text around it.
        - One blank line is the only separator: never two or more in a row, and never trailing spaces at the end of a line.
        - Lead with the answer, then the detail. No preamble ("Sure!", "Certainly"), no restating of my question, no sign-off.

        These rules cover spacing and characters. If the skill below specifies an exact output shape — a fixed set of labeled lines, a character limit, a single sentence — that shape wins: keep it exactly, and apply these rules inside it.
        """;
}
