#!/usr/bin/env python3
"""Regenerates the C# prompt constants from the macOS Swift sources.

The system prompts ARE the product, so they are not transcribed by hand and
they are not edited in C#. Edit the Swift source, re-run this, commit the
generated files:

    python3 windows/tools/sync-prompts.py

Generated files end in `.g.cs` and carry a do-not-edit header.
"""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
SWIFT = ROOT / "Sources" / "MacOnScreenChat"
CORE = ROOT / "windows" / "src" / "OnScreenChat.Core"

HEADER = """// <auto-generated>
//     Generated from {source} by windows/tools/sync-prompts.py.
//     DO NOT EDIT BY HAND — edit the Swift source and re-run the generator,
//     so the macOS and Windows apps cannot drift apart.
// </auto-generated>
"""

SIMPLE_ESCAPES = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "\\": "\\", "0": "\0"}


def read_string(text: str, i: int) -> tuple[str, int]:
    """Reads the Swift string literal starting at `text[i]`; returns (value, end)."""
    if text.startswith('"""', i):
        return read_multiline(text, i)
    return read_simple(text, i)


def read_simple(text: str, i: int) -> tuple[str, int]:
    assert text[i] == '"'
    out, i = [], i + 1
    while text[i] != '"':
        if text[i] == "\\":
            nxt = text[i + 1]
            if nxt not in SIMPLE_ESCAPES:
                raise ValueError(f"unhandled escape \\{nxt}")
            out.append(SIMPLE_ESCAPES[nxt])
            i += 2
            continue
        out.append(text[i])
        i += 1
    return "".join(out), i + 1


def read_multiline(text: str, i: int) -> tuple[str, int]:
    end = text.index('"""', i + 3)
    body = text[i + 3 : end]

    # Swift strips the closing delimiter's indentation from every line, drops
    # the newline that follows the opening delimiter, and drops the last line.
    line_start = text.rindex("\n", 0, end) + 1
    indent = text[line_start:end]
    lines = body.split("\n")[1:-1]
    lines = [ln[len(indent):] if ln.startswith(indent) else ln.lstrip() for ln in lines]

    # A trailing backslash is a line continuation: join without a newline.
    joined: list[str] = []
    for line in lines:
        if joined and joined[-1].endswith("\\"):
            joined[-1] = joined[-1][:-1] + line
        else:
            joined.append(line)
    return decode_escapes("\n".join(joined)), end + 3


def decode_escapes(text: str) -> str:
    r"""Resolves Swift escape sequences, leaving `\(interpolation)` alone."""
    out, i = [], 0
    while i < len(text):
        if text[i] == "\\" and i + 1 < len(text) and text[i + 1] in SIMPLE_ESCAPES:
            out.append(SIMPLE_ESCAPES[text[i + 1]])
            i += 2
            continue
        out.append(text[i])
        i += 1
    return "".join(out)


def field(text: str, start: int, name: str) -> tuple[str, int]:
    """Reads `name: <string literal>` at or after `start`."""
    at = text.index(name + ":", start)
    i = at + len(name) + 1
    while text[i] in " \t\n":
        i += 1
    return read_string(text, i)


def assignment(text: str, name: str) -> str:
    """Reads `let <name> = <string literal>`."""
    i = text.index(name) + len(name)
    i = text.index("=", i) + 1
    while text[i] in " \t\n":
        i += 1
    return read_string(text, i)[0]


def csharp_raw(value: str, indent: str) -> str:
    if '"""' in value:
        raise ValueError("prompt contains a raw-string delimiter; widen the fence")
    body = "\n".join(indent + ln if ln else "" for ln in value.split("\n"))
    return f'"""\n{body}\n{indent}"""'


def parse_skills() -> list[dict]:
    text = (SWIFT / "Models.swift").read_text(encoding="utf-8")
    start = text.index("static let defaults: [Skill] = [")
    skills, i = [], start
    while True:
        try:
            i = text.index("Skill(", i + 1)
        except ValueError:
            break
        skill = {}
        cursor = i
        for name in ("id", "name", "inputHint", "systemPrompt"):
            skill[name], cursor = field(text, cursor, name)
        order = re.search(r"sortOrder:\s*(\d+)", text[cursor:cursor + 200])
        skill["sortOrder"] = int(order.group(1))
        skills.append(skill)
        i = cursor
    return skills


def emit_skills(skills: list[dict]) -> str:
    out = [HEADER.format(source="Sources/MacOnScreenChat/Models.swift")]
    out.append("namespace OnScreenChat.Core.Data;\n")
    out.append("/// <summary>The skills seeded into SQLite on first launch.</summary>")
    out.append("public static class SkillDefaults\n{")
    out.append("    public static IReadOnlyList<Skill> All { get; } =\n    [")
    for skill in skills:
        out.append("        new Skill")
        out.append("        {")
        out.append(f'            Id = "{skill["id"]}",')
        out.append(f'            Name = "{skill["name"]}",')
        out.append(f'            InputHint = "{skill["inputHint"]}",')
        out.append(f'            SystemPrompt = {csharp_raw(skill["systemPrompt"], " " * 16)},')
        out.append(f'            SortOrder = {skill["sortOrder"]},')
        out.append("        },")
    out.append("    ];\n")
    out.append("    /// <summary>The skill used when nothing else is selected.</summary>")
    out.append("    public static Skill Fallback => All[0];")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_contract() -> str:
    text = (SWIFT / "ResponseStyle.swift").read_text(encoding="utf-8")
    value = assignment(text, "static let contract")
    out = [HEADER.format(source="Sources/MacOnScreenChat/ResponseStyle.swift")]
    out.append("namespace OnScreenChat.Core.Text;\n")
    out.append("public static partial class ResponseStyle\n{")
    out.append("    /// <summary>Prepended to every system prompt, whatever the skill.</summary>")
    out.append(f"    public const string Contract = {csharp_raw(value, ' ' * 8)};")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_heat() -> str:
    text = (SWIFT / "DatingHeat.swift").read_text(encoding="utf-8")
    body = text[text.index("var promptDirective"):]
    cases = {}
    for case in ("cool", "warm", "spicy"):
        at = body.index(f"case .{case}:")
        quote = body.index('"', at)
        cases[case], _ = read_string(body, quote)
    out = [HEADER.format(source="Sources/MacOnScreenChat/DatingHeat.swift")]
    out.append("namespace OnScreenChat.Core.Prompts;\n")
    out.append("/// <summary>Calibration text appended to the dating skill's prompt.</summary>")
    out.append("internal static class DatingHeatText\n{")
    for case, value in cases.items():
        out.append(f"    public const string {case.capitalize()} =")
        out.append(f"        {csharp_raw(value, ' ' * 8)};\n")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_templates() -> str:
    """The two prompt blocks built around an interpolated value."""
    rules_src = (SWIFT / "RuleStore.swift").read_text(encoding="utf-8")
    rules = read_multiline(rules_src, rules_src.index('"""', rules_src.index("var promptBlock")))[0]

    vm_src = (SWIFT / "ChatViewModel.swift").read_text(encoding="utf-8")
    at = vm_src.index("HIGHEST-PRIORITY")
    directive = read_multiline(vm_src, vm_src.rindex('"""', 0, at))[0]

    def template(value: str, placeholder: str) -> str:
        # Escape braces for string.Format, then re-open the one real slot.
        return value.replace("{", "{{").replace("}", "}}").replace(placeholder, "{0}")

    out = [HEADER.format(source="Sources/MacOnScreenChat/{RuleStore,ChatViewModel}.swift")]
    out.append("namespace OnScreenChat.Core.Prompts;\n")
    out.append("/// <summary>Prompt blocks that wrap a runtime value; use with string.Format.</summary>")
    out.append("public static class PromptTemplates\n{")
    out.append("    /// <summary>{0} is the numbered list of standing rules.</summary>")
    out.append(f"    public const string StandingRules =\n        {csharp_raw(template(rules, chr(92) + '(list)'), ' ' * 8)};\n")
    out.append("    /// <summary>{0} is the one-shot directive text.</summary>")
    out.append(f"    public const string Directive =\n        {csharp_raw(template(directive, chr(92) + '(directive)'), ' ' * 8)};")
    out.append("}")
    return "\n".join(out) + "\n"


def write(path: Path, content: str, check: bool) -> bool:
    """Writes the file, or in check mode reports whether it is stale."""
    rel = path.relative_to(ROOT)
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            print(f"  ok     {rel}")
            return True
        print(f"  STALE  {rel}" if current else f"  MISSING {rel}")
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote  {rel}  ({len(content.splitlines())} lines)")
    return True


def main() -> int:
    check = "--check" in sys.argv
    skills = parse_skills()
    print(f"Parsed {len(skills)} skills from Models.swift: {', '.join(s['id'] for s in skills)}")

    ok = [
        write(CORE / "Data" / "SkillDefaults.g.cs", emit_skills(skills), check),
        write(CORE / "Text" / "ResponseStyleContract.g.cs", emit_contract(), check),
        write(CORE / "Prompts" / "DatingHeatText.g.cs", emit_heat(), check),
        write(CORE / "Prompts" / "PromptTemplates.g.cs", emit_templates(), check),
    ]

    if check and not all(ok):
        print("\nThe Windows prompts have drifted from the Swift source.")
        print("Re-run without --check and commit the result.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
